name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ https://gist.github.com/PCY00/ }}
          TIMEZONE: Asia/Seoul
